T2_Laulate_Maycol/Models/Distribuidor.cs
using System.ComponentModel.DataAnnotations;


namespace T2_Laulate_Maycol.Models
{
    public class Distribuidor
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre de Distribuidor es obligatorio")]
        public string NombreDistribuidor { get; set; }

        [Required(ErrorMessage = "La razon social es obligatorio")]
        public string RazonSocial { get; set; }

        [Required(ErrorMessage = "El telefono es obligatorio")]
        public int Telefono { get; set; }

        [Required(ErrorMessage = "El Año de inicio es obligatorio")]
        [Range(1900, 3000, ErrorMessage = "El año debe ser entre 1 y 3000")]
        public int AnioInicioOperacion { get; set; }

        [Required(ErrorMessage = "El contacto es obligatorio")]
        public string Contacto { get; set; }
    }
}

T2_Laulate_Maycol/Models/DistribuidorMundo.cs
using System.ComponentModel.DataAnnotations;

namespace T2_Laulate_Maycol.Models
{
    public class DistribuidorMundo
    {
        [Key]
        public int IdMundo { get; set; }
        public string NombreDistribuidorMundo { get; set; }
        public string RazonSocialMundo { get; set; }
        public int TelefonoMundo { get; set; }
        public int AnioInicioOperacionMundo { get; set; }
        public string ContactoMundo { get; set; }
    }
}

T2_Laulate_Maycol/Models/DistribuidorPeru.cs
using System.ComponentModel.DataAnnotations;

namespace T2_Laulate_Maycol.Models
{
    public class DistribuidorPeru
    {
        [Key]
        public int IdPeru { get; set; }
        public string NombreDistribuidorPeru { get; set; }
        public string RazonSocialPeru { get; set; }
        public int TelefonoPeru { get; set; }
        public int AnioInicioOperacionPeru { get; set; }
        public string ContactoPeru { get; set; }
    }
}

T2_Laulate_Maycol/Models/ErrorViewModel.cs
namespace T2_Laulate_Maycol.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

T2_Laulate_Maycol/Controllers/DistribuidorController.cs
using Microsoft.AspNetCore.Mvc;
using T2_Laulate_Maycol.Datos;
using T2_Laulate_Maycol.Models;

namespace T2_Laulate_Maycol.Controllers
{
    public class DistribuidorController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DistribuidorController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Distribuidor> lista = _db.Distribuidor;
            return View(lista);
        }

        public IActionResult Peru()
        {
            IEnumerable<DistribuidorPeru> distribuidoresPeru = _db.DistribuidorPE.ToList();
            return View(distribuidoresPeru);
        }

        public IActionResult Mundo()
        {
            IEnumerable<DistribuidorMundo> distribuidoresMundo = _db.DistribuidorMUNDO.ToList();
            return View(distribuidoresMundo);
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Add(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);

        }

    }
}

T2_Laulate_Maycol/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using T2_Laulate_Maycol.Models;

namespace T2_Laulate_Maycol.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

T2_Laulate_Maycol/Views/Distribuidor/Crear.cshtml
@model T2_Laulate_Maycol.Models.Distribuidor;
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<form method="post" asp-action="Crear">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-intro pl-3">Nuevo Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control" />
                    <span asp-validation-for="NombreDistribuidor" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razon Social</label>
                    <input asp-for="RazonSocial" class="form-control" />
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Anio de Inicio Operacion</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                    <span asp-validation-for="AnioInicioOperacion" class="text-danger"></span>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grid gap-2 d-md-block">

                <button type="submit" class="btn btn-primary">Crear Nueva</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>

            </div>

        </div>
    </div>

</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}          

T2_Laulate_Maycol/Views/Distribuidor/Index.cshtml
@model IEnumerable<T2_Laulate_Maycol.Models.Distribuidor>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container pt-3">

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Lista de Distribuidores</h2>

        </div>
        <div class="col-6">
            <a asp-controller="Distribuidor" asp-action="Crear" class="btn btn-primary">Ingrese nuevo Distribuidor</a>
        </div>

    </div>

    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> Nombre Distribuidor </th>
                    <th> Razon Social </th>
                    <th> Telefono </th>
                    <th> Anio inicio </th>
                    <th> Contacto </th>
                    <th>  </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="60%">@item.NombreDistribuidor</th>
                        <th width="50%">@item.RazonSocial</th>
                        <th width="40%">@item.Telefono</th>
                        <th width="30%">@item.AnioInicioOperacion</th>
                        <th width="20%">@item.Contacto</th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {

        <p>No hay registros en la categoria</p>
    }

</div>

T2_Laulate_Maycol/Views/Distribuidor/Mundo.cshtml
@model IEnumerable<T2_Laulate_Maycol.Models.DistribuidorMundo>
@{
    ViewData["Title"] = "Mundo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container pt-3">

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Lista de Distribuidores del Mundo</h2>

        </div>
        <div class="col-6">
            <a asp-controller="Distribuidor" asp-action="Crear" class="btn btn-primary">Ingrese nuevo Distribuidor</a>
        </div>

    </div>

    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> Nombre Distribuidor </th>
                    <th> Razon Social </th>
                    <th> Telefono </th>
                    <th> Anio inicio </th>
                    <th> Contacto </th>
                    <th>  </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="60%">@item.NombreDistribuidorMundo</th>
                        <th width="50%">@item.RazonSocialMundo</th>
                        <th width="40%">@item.TelefonoMundo</th>
                        <th width="30%">@item.AnioInicioOperacionMundo</th>
                        <th width="20%">@item.ContactoMundo</th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {

        <p>No hay registros en la categoria</p>
    }

</div>

T2_Laulate_Maycol/Views/Distribuidor/Peru.cshtml
@model IEnumerable<T2_Laulate_Maycol.Models.DistribuidorPeru>
@{
    ViewData["Title"] = "Peru";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container pt-3">

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Lista de Distribuidores del Peru</h2>

        </div>
        <div class="col-6">
            <a asp-controller="Distribuidor" asp-action="Crear" class="btn btn-primary">Ingrese nuevo Distribuidor</a>
        </div>

    </div>

    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> Nombre Distribuidor </th>
                    <th> Razon Social </th>
                    <th> Telefono </th>
                    <th> Anio inicio </th>
                    <th> Contacto </th>
                    <th>  </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="60%">@item.NombreDistribuidorPeru</th>
                        <th width="50%">@item.RazonSocialPeru</th>
                        <th width="40%">@item.TelefonoPeru</th>
                        <th width="30%">@item.AnioInicioOperacionPeru</th>
                        <th width="20%">@item.ContactoPeru</th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {

        <p>No hay registros en la categoria</p>
    }

</div>

T2_Laulate_Maycol/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

T2_Laulate_Maycol/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T2_laulate_Maycol</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T2_laulate_Maycol.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T2_laulate_Maycol</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Index">Distribuidor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Peru">Distribuidores Peru</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Mundo">Distribuidores del Mundo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - T2_laulate_Maycol - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>